import * as path from 'path';
import { fs, log, selectors, types } from 'vortex-api';
import { GAME_ID, MODTYPE_LOGICMODS, UE4SS_MODS_SUBPATH } from '../common';
import { getLoadOrder } from './loadOrderPrefix';

// BPModLoaderMod (shipped inside UE4SS) decides blueprint mod load order purely from
// this file. One mod name per line, without the .pak extension, top to bottom.
// The pak file names themselves must NOT be touched: BPModLoaderMod derives each
// mod's asset path from the file name (/Game/Mods/<pakName>/ModActor), so renaming
// a pak stops the mod from loading at all.
const BPMODLOADER_SUBPATH = path.join(UE4SS_MODS_SUBPATH, 'BPModLoaderMod');
const LOAD_ORDER_FILE = 'load_order.txt';

// A previous version briefly deployed LogicMods paks with a 3-letter load-order
// prefix (AAA_Foo.pak). That broke BPModLoaderMod (it derives the asset path from
// the file name) and left orphaned duplicates behind. Nothing creates these any
// more, so any pak matching this shape is stale and safe to delete.
const STALE_MERGE_PAK_RE = /^[A-Y]{3}_.+\.pak$/i;

function logicModsDir(gamePath: string): string {
  return path.join(gamePath, 'EscapeTheBackrooms', 'Content', 'Paks', 'LogicMods');
}

/**
 * Remove stale prefixed LogicMods paks left behind by the old merge approach.
 * Safe to call any time, it only touches files matching the old AAA_ prefix.
 */
export async function cleanupStaleLogicModPaks(api: types.IExtensionApi): Promise<void> {
  const state = api.getState();
  const gamePath: string | undefined = state.settings.gameMode.discovered?.[GAME_ID]?.path;
  if (!gamePath) return;

  const dir = logicModsDir(gamePath);
  let entries: string[];
  try {
    entries = await fs.readdirAsync(dir);
  } catch (err: any) {
    if (err?.code !== 'ENOENT') log('warn', 'cleanupStaleLogicModPaks: could not list LogicMods', err);
    return;
  }

  for (const f of entries) {
    if (!STALE_MERGE_PAK_RE.test(f)) continue;
    try {
      await fs.unlinkAsync(path.join(dir, f));
      log('info', 'Removed stale prefixed LogicMods pak left by old merger', f);
    } catch (err) {
      log('warn', 'Could not remove stale LogicMods pak', { file: f, err });
    }
  }
}

const HEADER = [
  '; Load order generated by Vortex. Edit the load order in Vortex instead of this file.',
  '; BP mods are loaded top to bottom. Mods not listed load in a random order afterwards.',
];

/** Collect the .pak base names (no extension) a mod stages into LogicMods. */
async function pakNamesForMod(stagingRoot: string, modId: string): Promise<string[]> {
  const logicModsDir = path.join(stagingRoot, modId, 'EscapeTheBackrooms', 'Content', 'Paks', 'LogicMods');
  try {
    const entries: string[] = await fs.readdirAsync(logicModsDir);
    return entries
      .filter(f => path.extname(f).toLowerCase() === '.pak')
      .map(f => path.basename(f, path.extname(f)));
  } catch (err: any) {
    if (err?.code !== 'ENOENT') {
      log('warn', 'Could not list LogicMods paks for mod', { modId, err });
    }
    return [];
  }
}

/**
 * Write BPModLoaderMod/load_order.txt from the Vortex load order.
 * No-op when the game isn't discovered or UE4SS/BPModLoaderMod isn't installed.
 */
export async function writeBPModLoadOrder(api: types.IExtensionApi): Promise<void> {
  const state = api.getState();
  const gamePath: string | undefined = state.settings.gameMode.discovered?.[GAME_ID]?.path;
  if (!gamePath) return;

  const bpModLoaderDir = path.join(gamePath, 'EscapeTheBackrooms', 'Binaries', 'Win64', BPMODLOADER_SUBPATH);
  // Only write if BPModLoaderMod is actually present (i.e. a mod loader is installed).
  const installed = await fs.statAsync(bpModLoaderDir).then(() => true).catch(() => false);
  if (!installed) {
    log('debug', 'BPModLoaderMod not installed, skipping load_order.txt');
    return;
  }

  const mods: Record<string, types.IMod> = (state as any).persistent?.mods?.[GAME_ID] ?? {};
  const stagingRoot: string = selectors.installPathForGame(state, GAME_ID);
  const loadOrder = getLoadOrder(api, GAME_ID);

  const names: string[] = [];
  for (const entry of loadOrder) {
    const modId = entry?.id;
    if (!modId) continue;
    const mod = mods[modId];
    if (mod?.type !== MODTYPE_LOGICMODS) continue;
    for (const name of await pakNamesForMod(stagingRoot, modId)) {
      if (!names.includes(name)) names.push(name);
    }
  }

  const target = path.join(bpModLoaderDir, LOAD_ORDER_FILE);
  // BPModLoaderMod reads this with Lua io.lines and matches each entry against the
  // pak name with an exact string compare (no trimming). Write plain '\n', the same
  // convention the loader's own mods.txt uses, so a trailing '\r' never sneaks onto a
  // mod name and silently breaks the order match.
  const document = [...HEADER, ...names].join('\n') + '\n';
  try {
    await fs.writeFileAsync(target, document, { encoding: 'utf8' });
    log('debug', 'Wrote BPModLoader load order', { count: names.length });
  } catch (err) {
    log('error', 'Could not write BPModLoader load_order.txt', { target, err });
  }
}
